name: GoldRushMC
version: 1.1
description: The plugin created to facilitate the Gold Rush Server Features
author: Diremonsoon, lexwebb
database: true
#website: http://forums.bukkit.org/threads/ GET NEW WEBSITE ADDRESS AND APPEND

main: com.goldrushmc.bukkit.main.Main

commands:
  train:
   description: Tree for train creation
   aliases: [train]
   permission: goldrushmc.train.create
   usage: |
           Two types of train: Public or Standard
           /<command> [Standard, trainName, trainType, speedLimit]
           /<command> [Custom, trainName, trainType, numberOfPassengers, numberOfChestCarts, speedLimit]
           /<command> [Passenger, trainName, trainType, numberOfPassengers, speedLimit]
           /<command> [Storage, trainName, trainType, numberOfStorageCarts, speedLimit]
   
  wand:
   description: Wand which is used for marking the train spawn locations
   aliases: [wand, traintool]
   permission: goldrushmc.train.wand
   usage: /<command>

  cart:
   description: 
   aliases: [cart, addcart, c]
   permission: goldrushmc.train.add
   usage: /<command> [trainName, typeOfCart]
 
permissions:
  goldrushmc.*:
    description: Gives access to all commands to the plugin
    children:
      goldrushmc.train.create: true
      goldrushmc.train.wand: true
  goldrushmc.train.create:
    description: Allows you to create trains
    default: true

  goldrushmc.train.wand:
    description: Allows you to spawn the train wand
    default: true