name: GoldRushMC
version: 1.2
description: The plugin created to facilitate the Gold Rush Server Features
author: Diremonsoon, lexwebb, 1SmallVille1
database: true
#website: http://forums.bukkit.org/threads/ GET NEW WEBSITE ADDRESS AND APPEND

main: com.goldrushmc.bukkit.main.Main

commands:
  fall:

  stationwand:
   description: Wand which is used for marking the train stations
   aliases: [stationtool, stool]
   permission: goldrushmc.station.create
   usage: /<command>
 
  station:
   description: Tree for station creation.
   aliases: [station, st]
   permission: goldrushmc.station.create
   usage: /<command> [stationType, stationName]
   
permissions:
  goldrushmc.*:
    description: Gives access to all commands to the plugin
    children:
     goldrushmc.station.create: true
  goldrushmc.station.create:
    description: Allows you to spawn the station wand and make stations.
    default: true
